require "open-uri"
require "nokogiri"
require "pry"
require_relative "./wired_awaker/version"
require_relative "./wired_awaker/stories"
require_relative "./wired_awaker/cli"
require_relative "./wired_awaker/scraper"
require_relative "./wired_awaker/weekdays"